In [1]:
import pandas as pd

# Clean column names
columns = [
    "hackathon_name",
    "project_name",
    "project_link",
    "is_winner",
    "inspiration",
    "what_it_does",
    "how_we_built_it",
    "challenges",
    "accomplishments",
    "what_we_learned",
    "tech_stack",
    "external_links",
    "github_links",
    "github_summary"
]

# Load CSV
df = pd.read_csv("repo_analysis_results.csv", header=0, names=columns,index_col=False)

# Optional: reset index just for neatness
#df.reset_index(drop=True, inplace=True)

# --- Clean up ---
# Drop rows missing key info (as before)
df

C:\Users\gauur\AppData\Local\Temp\ipykernel_27928\4176860475.py:22: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv("repo_analysis_results.csv", header=0, names=columns,index_col=False)

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary
0,Cal Hacks 10.0,Audiogroph,https://devpost.com/software/audiogroph,False,With covid ending and people finding new music...,"The project shows events, creators and any NFT...",We used react to build it in vscode and collab...,We had to learn react and navigate through git...,We have successfully built the frontend of the...,Start planning earlier and commit to branches ...,We need a backend to our project.,"css3, html5, javascript, react",['https://github.com/RyanGertz/CalHacksproject'],['https://github.com/RyanGertz/CalHacksproject']
1,Cal Hacks 10.0,Let It Out,https://devpost.com/software/let-it-out-b2xp8u,False,Understanding and expressing emotions can be a...,The user is first prompted to record a vocal b...,Let It Out is a full stack web app. The front ...,The main challenges we ran into came in our fi...,NaN,We learned how to integrate modern technologie...,NaN,"chakra, flask, hume, mongodb, node.js, openai,...","['https://github.com/apolyeti/calhacks10.0,', ...",['https://github.com/apolyeti/calhacks10.0']
2,Cal Hacks 10.0,Mood Theremin,https://devpost.com/software/mood-theremin,False,"The theremin, an electronic musical instrument...",Mood Theremin translates your facial expressio...,Our project integrates facial expression analy...,NaN,NaN,NaN,NaN,"css, flask, html, hume, javascript, json, pyth...",['https://github.com/Sepulchre49/CalHacks23'],['https://github.com/Sepulchre49/CalHacks23']
3,Cal Hacks 10.0,Bay Area Safer Housing (B.A.S.H.),https://devpost.com/software/bay-area-safer-ho...,False,The inspiration initially stems from one membe...,B.A.S.H. searches for affordable housing optio...,Our website's foundation was built on next.js ...,Our difficulties lay in our inexperience with ...,"Conceptually, we believe that our project is m...",We've learned most importantly how to better a...,We are serious in our project and are intent o...,"catalog.data.gov, data.sfgov.org, google-maps,...","['https://github.com/matthewaol/b.a.s.h.,']",['https://github.com/matthewaol/b.a.s.h.']
4,Cal Hacks 10.0,PawPals,https://devpost.com/software/pawpals-bd8njs,False,"As college students, we both agreed that fun t...","Based on a list of criteria, we prompt OpenAI'...","On the front-end, we utilized Figma to develop...",Some challenges we ran into were the lack of e...,"As a team of two, we were very proud of our fi...",We learned the value of coming up with a plan ...,We hope to deploy the site on Vercel and devel...,"fastapi, figma, openai, python, react.js, sqlite",['https://github.com/Yatsz/PawPals'],['https://github.com/Yatsz/PawPals']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1833,HackRice 14 2024,Degree Map AI,https://devpost.com/software/degree-planner-ai,False,As current undergraduate students trying to na...,Degree Map AI includes a React front-end and a...,"We first started by working on the scraper, fr...",One challenge we faced was figuring out the be...,We're proud to have successfully connected the...,"We learned to set up OpenAI's ChatGPT, scrape ...","Given the limited amount of time, we were only...","c++, javascript, openai, pyflask, python, react",['https://github.com/april2546/HackRice2024'],['https://github.com/april2546/HackRice2024']
1834,HackRice 14 2024,Money Mania,https://devpost.com/software/money-mania,False,Our inspiration for this project was this book...,This game teaches people about personal financ...,We built this in Python using PyGame. We split...,None of us have ever participated in a hackath...,We are proud of the fact we have a finished pr...,We learned that creating a layout in PyGame is...,Money Mania will have expansions in the invest...,"pygame, python",['https://github.com/ashwinrao1/Hackathon24'],['https://github.com/ashwinrao1/Hackathon24']
1835,HackRice 14 2024,AudioAnalyze,https://devpost.com/software/audioanalyze-muw9zk,False,The inspiration behind this project came from ...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, generative, lambda-(for-serverless-process...",['https://github.com/Ayush374/Ai_Audio_Analysis'],['https://github.com/Ayush374/Ai_Audio_Analysis']
1836,HackRice 14 2024,RestoreIO,https://devpost.com/software/tbd-ir3qd5,False,RestoreIO was created in response to the deman...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, computer, computervision, love, mediapipe,...",['https://github.com/OfficialCodeVoyage/HackRi...,['https://github.com/OfficialCodeVoyage/HackRi...
1837,HackRice 14 2024,MedSure,https://devpost.com/software/tbd-72iomb,False,"As young college students, we are often poorly...",Our key features: 1) Simplify the insurance hu...,Since we wanted to implement a machine learnin...,NaN,NaN,NaN,NaN,"mapbox, python, typescript, vite",['https://github.com/leon934/hackrice2425'],['https://github.com/leon934/hackrice2425']

In [2]:
df.hackathon_name.unique()

array(['Cal Hacks 10.0', 'TreeHacks 2023', 'HackGT X',
       'Hack the Valley 8', 'HackDuke 2023', 'HackIllinois 2023',
       'ShellHacks 2024', 'HackHarvard 2024', 'TreeHacks 2024',
       'HackNJIT 2024', 'LAHacks 2024', 'HackIllinois 2024',
       'PennApps XXV 2024', 'VTHacks 12 2024', 'TAMUhack X 2024',
       'HackRice 14 2024'], dtype=object)

In [3]:
df.isna().sum()

hackathon_name       0
project_name         0
project_link         0
is_winner            0
inspiration          0
what_it_does       362
how_we_built_it    449
challenges         507
accomplishments    551
what_we_learned    557
tech_stack         520
external_links       0
github_links         0
github_summary       0
dtype: int64

In [4]:
before = len(df)
df = df.dropna(subset=["inspiration", "github_summary"])
after = len(df)

print(f"Removed {before - after} rows (kept {after})")

Removed 0 rows (kept 1838)

In [5]:
df

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary
0,Cal Hacks 10.0,Audiogroph,https://devpost.com/software/audiogroph,False,With covid ending and people finding new music...,"The project shows events, creators and any NFT...",We used react to build it in vscode and collab...,We had to learn react and navigate through git...,We have successfully built the frontend of the...,Start planning earlier and commit to branches ...,We need a backend to our project.,"css3, html5, javascript, react",['https://github.com/RyanGertz/CalHacksproject'],['https://github.com/RyanGertz/CalHacksproject']
1,Cal Hacks 10.0,Let It Out,https://devpost.com/software/let-it-out-b2xp8u,False,Understanding and expressing emotions can be a...,The user is first prompted to record a vocal b...,Let It Out is a full stack web app. The front ...,The main challenges we ran into came in our fi...,NaN,We learned how to integrate modern technologie...,NaN,"chakra, flask, hume, mongodb, node.js, openai,...","['https://github.com/apolyeti/calhacks10.0,', ...",['https://github.com/apolyeti/calhacks10.0']
2,Cal Hacks 10.0,Mood Theremin,https://devpost.com/software/mood-theremin,False,"The theremin, an electronic musical instrument...",Mood Theremin translates your facial expressio...,Our project integrates facial expression analy...,NaN,NaN,NaN,NaN,"css, flask, html, hume, javascript, json, pyth...",['https://github.com/Sepulchre49/CalHacks23'],['https://github.com/Sepulchre49/CalHacks23']
3,Cal Hacks 10.0,Bay Area Safer Housing (B.A.S.H.),https://devpost.com/software/bay-area-safer-ho...,False,The inspiration initially stems from one membe...,B.A.S.H. searches for affordable housing optio...,Our website's foundation was built on next.js ...,Our difficulties lay in our inexperience with ...,"Conceptually, we believe that our project is m...",We've learned most importantly how to better a...,We are serious in our project and are intent o...,"catalog.data.gov, data.sfgov.org, google-maps,...","['https://github.com/matthewaol/b.a.s.h.,']",['https://github.com/matthewaol/b.a.s.h.']
4,Cal Hacks 10.0,PawPals,https://devpost.com/software/pawpals-bd8njs,False,"As college students, we both agreed that fun t...","Based on a list of criteria, we prompt OpenAI'...","On the front-end, we utilized Figma to develop...",Some challenges we ran into were the lack of e...,"As a team of two, we were very proud of our fi...",We learned the value of coming up with a plan ...,We hope to deploy the site on Vercel and devel...,"fastapi, figma, openai, python, react.js, sqlite",['https://github.com/Yatsz/PawPals'],['https://github.com/Yatsz/PawPals']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1833,HackRice 14 2024,Degree Map AI,https://devpost.com/software/degree-planner-ai,False,As current undergraduate students trying to na...,Degree Map AI includes a React front-end and a...,"We first started by working on the scraper, fr...",One challenge we faced was figuring out the be...,We're proud to have successfully connected the...,"We learned to set up OpenAI's ChatGPT, scrape ...","Given the limited amount of time, we were only...","c++, javascript, openai, pyflask, python, react",['https://github.com/april2546/HackRice2024'],['https://github.com/april2546/HackRice2024']
1834,HackRice 14 2024,Money Mania,https://devpost.com/software/money-mania,False,Our inspiration for this project was this book...,This game teaches people about personal financ...,We built this in Python using PyGame. We split...,None of us have ever participated in a hackath...,We are proud of the fact we have a finished pr...,We learned that creating a layout in PyGame is...,Money Mania will have expansions in the invest...,"pygame, python",['https://github.com/ashwinrao1/Hackathon24'],['https://github.com/ashwinrao1/Hackathon24']
1835,HackRice 14 2024,AudioAnalyze,https://devpost.com/software/audioanalyze-muw9zk,False,The inspiration behind this project came from ...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, generative, lambda-(for-serverless-process...",['https://github.com/Ayush374/Ai_Audio_Analysis'],['https://github.com/Ayush374/Ai_Audio_Analysis']
1836,HackRice 14 2024,RestoreIO,https://devpost.com/software/tbd-ir3qd5,False,RestoreIO was created in response to the deman...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, computer, computervision, love, mediapipe,...",['https://github.com/OfficialCodeVoyage/HackRi...,['https://github.com/OfficialCodeVoyage/HackRi...
1837,HackRice 14 2024,MedSure,https://devpost.com/software/tbd-72iomb,False,"As young college students, we are often poorly...",Our key features: 1) Simplify the insurance hu...,Since we wanted to implement a machine learnin...,NaN,NaN,NaN,NaN,"mapbox, python, typescript, vite",['https://github.com/leon934/hackrice2425'],['https://github.com/leon934/hackrice2425']

In [6]:
df2 = pd.read_csv("zhou_tst.csv", header=0, names=columns,index_col=False)
df2

C:\Users\gauur\AppData\Local\Temp\ipykernel_27928\2775658771.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df2 = pd.read_csv("zhou_tst.csv", header=0, names=columns,index_col=False)

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary
0,Auburn Hacks 2024,Courage The Not-so Cowardly Rover,https://devpost.com/software/courage-the-not-s...,True,Our inspiration came from the resources NASA p...,"In this Mars Rover educational game, players e...",NaN,NaN,NaN,NaN,NaN,"blendr, c#, mixtral, nasa, nginx, ollama, unity",['https://github.com/abearinatrap/auburnhack20...,['https://github.com/abearinatrap/auburnhack20...
1,Auburn Hacks 2024,Orbital Sandbox,https://devpost.com/software/orbital-sandbox,True,Interplanetary space exploration is becoming a...,The simulator allows you to fly a spacecraft a...,"The app was built in the Unity game-engine, wh...",The primary challenge for the design was build...,We are very proud of the real-time simulation ...,NaN,"Hopefully, after the completion of AuburnHACKS...","c#, unity",['https://github.com/EirikMulder/HackEpicUnity...,['https://github.com/EirikMulder/HackEpicUnity...
2,Auburn Hacks 2024,OrbitQuest,https://devpost.com/software/orbitquest,True,The theme this year is space travel. So why no...,OrbitQuesttracks the ISS as it travels around ...,We usedthree.jsfor the 3-D graphics portion of...,One significant challenge we faced was maintai...,We are extremely proud of the appearance of ou...,NaN,"In the future, we want to implement real-time ...","css, debian, digitalocean, django, git, github...",['https://github.com/TheSlabby/OrbitQuest'],['https://github.com/TheSlabby/OrbitQuest']
3,Auburn Hacks 2024,Pseduo,https://devpost.com/software/pseduo,True,The lack of ability to ask questions to trustw...,It allows people with minimal coding experienc...,"We used T3 stack (React, TypeScript, NextJs, T...",Auth0 struggled to work with TypeScript and we...,"Fully functional API, some pretty good UI for ...",NaN,NaN,"auth0, express.js, javascript, mongodb, nextjs...",['https://github.com/TrevorAupperle/pseudo'],['https://github.com/TrevorAupperle/pseudo']
4,Auburn Hacks 2024,Auburn Quest,https://devpost.com/software/auburn-quest,True,"We, the project developers, are international ...",Auburn Quest is a web-based application that h...,Our tech stack consists of the following:,Identifying the most important features to be ...,We are extremely proud of building the followi...,This is the first time we were able to use Mon...,We intend to demo this application to the Aubu...,"auth0, bootstrap, cloudflare, express.js, mong...",['https://github.com/lmedury/auburn-hacks-back...,['https://github.com/lmedury/auburn-hacks-back...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,VTHacks 12,Organic Food FInder,https://devpost.com/software/organic-food-finder,False,I am into health and neuroscience. \r\nUS has ...,AI powered search of organic foods based on us...,NaN,Getting APIs,It's working,Web app deployment,Include Map interface.,"beautiful-soup, openai, python",['https://github.com/danpartigiano/VTHAX2024'],['https://github.com/danpartigiano/VTHAX2024']
801,VTHacks 12,SquatMap,https://devpost.com/software/squatmap,False,"Our project, ""SquatDown,"" has goal to assist ...",NaN,NaN,NaN,NaN,NaN,NaN,"css, google-maps, html, javascript, node.js, r...",['https://github.com/harshalarakala/squatdown'],['https://github.com/harshalarakala/squatdown']
802,VTHacks 12,OriGaming,https://devpost.com/software/origaming,False,"Since high school, we have had an interest in ...","0rigAmIng is a ""paper-folding simulator"" that ...",We built 0rigAmIng fully in Godot Engine 3D.,"Where do we even begin? To start, none of us h...",Our first big strides in the project were when...,"Well, we learned that hackathons are crazy! Bu...",NaN,godot,['https://github.com/vaaar/OriGaming'],['https://github.com/vaaar/OriGaming']
803,VTHacks 12,Ask Hokie,https://devpost.com/software/hokie-plus-plus,False,Ask HOKIE Problem Statement Technical Framewor...,NaN,NaN,NaN,NaN,NaN,NaN,"css3, gpt, llm, mlh, mongodb, propelauth, react",['https://github.com/mahatokunal/askHokie'],['https://github.com/mahatokunal/askHokie']
804,VTHacks 12,internot.blog,https://devpost.com/software/internot-blog,False,Inspired by the concept of the 'dead internet ...,Internot.blog is a blog website where every po...,We set up and used a locally hosted instance o...,Generating images that don't look like complet...,The system is able to operate entirely autonom...,AI is really good at making up stories about e...,We will let it run and generate new content fo...,"css3, go, html5, hugo, llama3.1, rust, stable-...",['https://github.com/internot-blog'],['https://github.com/internot-blog']

In [7]:
df2.is_winner.value_counts()

is_winner
False    636
True     169
Name: count, dtype: int64

In [8]:
before = len(df2)
df2 = df2.dropna(subset=["inspiration", "github_summary"])
after = len(df2)

print(f"Removed {before - after} rows (kept {after})")

Removed 0 rows (kept 805)

In [9]:
df2

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary
0,Auburn Hacks 2024,Courage The Not-so Cowardly Rover,https://devpost.com/software/courage-the-not-s...,True,Our inspiration came from the resources NASA p...,"In this Mars Rover educational game, players e...",NaN,NaN,NaN,NaN,NaN,"blendr, c#, mixtral, nasa, nginx, ollama, unity",['https://github.com/abearinatrap/auburnhack20...,['https://github.com/abearinatrap/auburnhack20...
1,Auburn Hacks 2024,Orbital Sandbox,https://devpost.com/software/orbital-sandbox,True,Interplanetary space exploration is becoming a...,The simulator allows you to fly a spacecraft a...,"The app was built in the Unity game-engine, wh...",The primary challenge for the design was build...,We are very proud of the real-time simulation ...,NaN,"Hopefully, after the completion of AuburnHACKS...","c#, unity",['https://github.com/EirikMulder/HackEpicUnity...,['https://github.com/EirikMulder/HackEpicUnity...
2,Auburn Hacks 2024,OrbitQuest,https://devpost.com/software/orbitquest,True,The theme this year is space travel. So why no...,OrbitQuesttracks the ISS as it travels around ...,We usedthree.jsfor the 3-D graphics portion of...,One significant challenge we faced was maintai...,We are extremely proud of the appearance of ou...,NaN,"In the future, we want to implement real-time ...","css, debian, digitalocean, django, git, github...",['https://github.com/TheSlabby/OrbitQuest'],['https://github.com/TheSlabby/OrbitQuest']
3,Auburn Hacks 2024,Pseduo,https://devpost.com/software/pseduo,True,The lack of ability to ask questions to trustw...,It allows people with minimal coding experienc...,"We used T3 stack (React, TypeScript, NextJs, T...",Auth0 struggled to work with TypeScript and we...,"Fully functional API, some pretty good UI for ...",NaN,NaN,"auth0, express.js, javascript, mongodb, nextjs...",['https://github.com/TrevorAupperle/pseudo'],['https://github.com/TrevorAupperle/pseudo']
4,Auburn Hacks 2024,Auburn Quest,https://devpost.com/software/auburn-quest,True,"We, the project developers, are international ...",Auburn Quest is a web-based application that h...,Our tech stack consists of the following:,Identifying the most important features to be ...,We are extremely proud of building the followi...,This is the first time we were able to use Mon...,We intend to demo this application to the Aubu...,"auth0, bootstrap, cloudflare, express.js, mong...",['https://github.com/lmedury/auburn-hacks-back...,['https://github.com/lmedury/auburn-hacks-back...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,VTHacks 12,Organic Food FInder,https://devpost.com/software/organic-food-finder,False,I am into health and neuroscience. \r\nUS has ...,AI powered search of organic foods based on us...,NaN,Getting APIs,It's working,Web app deployment,Include Map interface.,"beautiful-soup, openai, python",['https://github.com/danpartigiano/VTHAX2024'],['https://github.com/danpartigiano/VTHAX2024']
801,VTHacks 12,SquatMap,https://devpost.com/software/squatmap,False,"Our project, ""SquatDown,"" has goal to assist ...",NaN,NaN,NaN,NaN,NaN,NaN,"css, google-maps, html, javascript, node.js, r...",['https://github.com/harshalarakala/squatdown'],['https://github.com/harshalarakala/squatdown']
802,VTHacks 12,OriGaming,https://devpost.com/software/origaming,False,"Since high school, we have had an interest in ...","0rigAmIng is a ""paper-folding simulator"" that ...",We built 0rigAmIng fully in Godot Engine 3D.,"Where do we even begin? To start, none of us h...",Our first big strides in the project were when...,"Well, we learned that hackathons are crazy! Bu...",NaN,godot,['https://github.com/vaaar/OriGaming'],['https://github.com/vaaar/OriGaming']
803,VTHacks 12,Ask Hokie,https://devpost.com/software/hokie-plus-plus,False,Ask HOKIE Problem Statement Technical Framewor...,NaN,NaN,NaN,NaN,NaN,NaN,"css3, gpt, llm, mlh, mongodb, propelauth, react",['https://github.com/mahatokunal/askHokie'],['https://github.com/mahatokunal/askHokie']
804,VTHacks 12,internot.blog,https://devpost.com/software/internot-blog,False,Inspired by the concept of the 'dead internet ...,Internot.blog is a blog website where every po...,We set up and used a locally hosted instance o...,Generating images that don't look like complet...,The system is able to operate entirely autonom...,AI is really good at making up stories about e...,We will let it run and generate new content fo...,"css3, go, html5, hugo, llama3.1, rust, stable-...",['https://github.com/internot-blog'],['https://github.com/internot-blog']

In [10]:
df_new = pd.concat([df, df2], ignore_index=True)
df_new

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary
0,Cal Hacks 10.0,Audiogroph,https://devpost.com/software/audiogroph,False,With covid ending and people finding new music...,"The project shows events, creators and any NFT...",We used react to build it in vscode and collab...,We had to learn react and navigate through git...,We have successfully built the frontend of the...,Start planning earlier and commit to branches ...,We need a backend to our project.,"css3, html5, javascript, react",['https://github.com/RyanGertz/CalHacksproject'],['https://github.com/RyanGertz/CalHacksproject']
1,Cal Hacks 10.0,Let It Out,https://devpost.com/software/let-it-out-b2xp8u,False,Understanding and expressing emotions can be a...,The user is first prompted to record a vocal b...,Let It Out is a full stack web app. The front ...,The main challenges we ran into came in our fi...,NaN,We learned how to integrate modern technologie...,NaN,"chakra, flask, hume, mongodb, node.js, openai,...","['https://github.com/apolyeti/calhacks10.0,', ...",['https://github.com/apolyeti/calhacks10.0']
2,Cal Hacks 10.0,Mood Theremin,https://devpost.com/software/mood-theremin,False,"The theremin, an electronic musical instrument...",Mood Theremin translates your facial expressio...,Our project integrates facial expression analy...,NaN,NaN,NaN,NaN,"css, flask, html, hume, javascript, json, pyth...",['https://github.com/Sepulchre49/CalHacks23'],['https://github.com/Sepulchre49/CalHacks23']
3,Cal Hacks 10.0,Bay Area Safer Housing (B.A.S.H.),https://devpost.com/software/bay-area-safer-ho...,False,The inspiration initially stems from one membe...,B.A.S.H. searches for affordable housing optio...,Our website's foundation was built on next.js ...,Our difficulties lay in our inexperience with ...,"Conceptually, we believe that our project is m...",We've learned most importantly how to better a...,We are serious in our project and are intent o...,"catalog.data.gov, data.sfgov.org, google-maps,...","['https://github.com/matthewaol/b.a.s.h.,']",['https://github.com/matthewaol/b.a.s.h.']
4,Cal Hacks 10.0,PawPals,https://devpost.com/software/pawpals-bd8njs,False,"As college students, we both agreed that fun t...","Based on a list of criteria, we prompt OpenAI'...","On the front-end, we utilized Figma to develop...",Some challenges we ran into were the lack of e...,"As a team of two, we were very proud of our fi...",We learned the value of coming up with a plan ...,We hope to deploy the site on Vercel and devel...,"fastapi, figma, openai, python, react.js, sqlite",['https://github.com/Yatsz/PawPals'],['https://github.com/Yatsz/PawPals']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2638,VTHacks 12,Organic Food FInder,https://devpost.com/software/organic-food-finder,False,I am into health and neuroscience. \r\nUS has ...,AI powered search of organic foods based on us...,NaN,Getting APIs,It's working,Web app deployment,Include Map interface.,"beautiful-soup, openai, python",['https://github.com/danpartigiano/VTHAX2024'],['https://github.com/danpartigiano/VTHAX2024']
2639,VTHacks 12,SquatMap,https://devpost.com/software/squatmap,False,"Our project, ""SquatDown,"" has goal to assist ...",NaN,NaN,NaN,NaN,NaN,NaN,"css, google-maps, html, javascript, node.js, r...",['https://github.com/harshalarakala/squatdown'],['https://github.com/harshalarakala/squatdown']
2640,VTHacks 12,OriGaming,https://devpost.com/software/origaming,False,"Since high school, we have had an interest in ...","0rigAmIng is a ""paper-folding simulator"" that ...",We built 0rigAmIng fully in Godot Engine 3D.,"Where do we even begin? To start, none of us h...",Our first big strides in the project were when...,"Well, we learned that hackathons are crazy! Bu...",NaN,godot,['https://github.com/vaaar/OriGaming'],['https://github.com/vaaar/OriGaming']
2641,VTHacks 12,Ask Hokie,https://devpost.com/software/hokie-plus-plus,False,Ask HOKIE Problem Statement Technical Framewor...,NaN,NaN,NaN,NaN,NaN,NaN,"css3, gpt, llm, mlh, mongodb, propelauth, react",['https://github.com/mahatokunal/askHokie'],['https://github.com/mahatokunal/askHokie']
2642,VTHacks 12,internot.blog,https://devpost.com/software/internot-blog,False,Inspired by the concept of the 'dead internet ...,Internot.blog is a blog website where every po...,We set up and used a locally hosted instance o...,Generating images that don't look like complet...,The system is able to operate entirely autonom...,AI is really good at making up stories about e...,We will let it run and generate new content fo...,"css3, go, html5, hugo, llama3.1, rust, stable-...",['https://github.com/internot-blog'],['https://github.com/internot-blog']

In [11]:
df_new.is_winner.value_counts()

is_winner
False    2173
True      470
Name: count, dtype: int64

In [15]:
df3 = pd.read_csv("more_data.csv")
df3 = df3.loc[:, ~df3.columns.str.contains('^Unnamed')]
df3

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,what_is_next,tech_stack,external_links,github_links,github_summary
0,Hack The North 2020,QuaranTime,https://devpost.com/software/boredombuster-hnimzc,True,Due to being stuck at home during Quarantine s...,QuaranTime is an app where a schedule is gener...,We decided to face a new challenge. Due to the...,There were many challenges that we faced. One ...,We are proud of the ability to use the Google ...,We were able to learn much more than expected ...,"If we had more time, we would add features suc...","dart, flutter, googleapis",['https://github.com/JackFrostDJ/HTN-App/tree/...,['https://github.com/JackFrostDJ/HTN-App/tree/...,"This repository, named HTN-App, appears to be ..."
1,Hack The North 2020,FridgeSpace,https://devpost.com/software/fridgespace,True,Based on the observation that most household w...,FridgeSpace allows household users to locate a...,We began by creating designs for our app using...,The biggest challenge we had to face was learn...,NaN,There were many new technologies we learned in...,Future Steps for our team include working with...,"cockroachdb, flask, python, sqlalchemy, swift,...",['https://github.com/Harin329/FridgeSpace'],['https://github.com/Harin329/FridgeSpace'],FridgeSpace is a Hack the North 2020++ winning...
2,Hack The North 2020,helppier,https://devpost.com/software/helppier-k5lbru,True,Inspired by the newly born solidarity within t...,Helppier's goal is to encourage a new social n...,In order to build a decentralized network wher...,While the developers of the team have experien...,We are extremely proud to have been able to de...,NaN,NaN,"azure, blockchain, cockroach.db, css3, express...","['https://github.com/aminecs/magic4,']",['https://github.com/aminecs/magic4'],**Repository Summary: Helppier - A Volunteerin...
3,Hack The North 2020,Mall Monitor,https://devpost.com/software/mall-monitor,True,Covid-19 has ravaged the World since early 202...,Mall Monitor allows owners and guests to monit...,NaN,NaN,NaN,NaN,Actually deploying and consuming the REST API ...,"angular.js, azure, css, flask, html, javascrip...","['https://github.com/RemeAjayi/mall-monitor,',...",['https://github.com/RemeAjayi/mall-monitor'],"This GitHub repository, named **mall-monitor**..."
4,Hack The North 2020,CAST3D - Scanner for Medicinal Casts,https://devpost.com/software/cast3d-scanner-fo...,True,With many previous fractures and injuries unde...,The CAST3D machine begins with the Alexa inter...,"We first built an Alexa skill using voiceflow,...",We are into many different challenges both har...,It worked! After several hardware and software...,"Making a system that combines hardware, softwa...","Hopefully, sometime in the future, a CAST3D V2...","arduino, google-spreadsheets, javascript, node...",['https://github.com/GKareem/CAST3D---Scanner-...,['https://github.com/GKareem/CAST3D---Scanner-...,"The GitHub repository ""CAST3D_HackTheNorth"" de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4360,HackRice 14 2024,Degree Map AI,https://devpost.com/software/degree-planner-ai,False,As current undergraduate students trying to na...,Degree Map AI includes a React front-end and a...,"We first started by working on the scraper, fr...",One challenge we faced was figuring out the be...,We're proud to have successfully connected the...,"We learned to set up OpenAI's ChatGPT, scrape ...","Given the limited amount of time, we were only...","c++, javascript, openai, pyflask, python, react",['https://github.com/april2546/HackRice2024'],['https://github.com/april2546/HackRice2024'],The HackRice2024-DegreeMapAI project is an inn...
4361,HackRice 14 2024,Money Mania,https://devpost.com/software/money-mania,False,Our inspiration for this project was this book...,This game teaches people about personal financ...,We built this in Python using PyGame. We split...,None of us have ever participated in a hackath...,We are proud of the fact we have a finished pr...,We learned that creating a layout in PyGame is...,Money Mania will have expansions in the invest...,"pygame, python",['https://github.com/ashwinrao1/Hackathon24'],['https://github.com/ashwinrao1/Hackathon24'],"The Hackathon24 project is a ""Personal Finance..."
4362,HackRice 14 2024,AudioAnalyze,https://devpost.com/software/audioanalyze-muw9zk,False,The inspiration behind this project came from ...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, generative, lambda-(for-serverless-process...",['https://github.com/Ayush374/Ai_Audio_Analysis'],['https://github.com/Ayush374/Ai_Audio_Analysis'],"The GitHub repository ""Ai_Audio_Analysis"" is d..."
4363,HackRice 14 2024,RestoreIO,https://devpost.com/software/tbd-ir3qd5,False,RestoreIO was created in response to the deman...,NaN,NaN,NaN,NaN,NaN,NaN,"ai, computer, computervision, love, mediapipe,...",['https://github.com/OfficialCodeVoyage/HackRi...,['https://github.com/OfficialCodeVoyage/HackRi...,"The GitHub repository ""HackRice14_RecoveryIO,""..."
4364,HackRice 14 2024,MedSure,https://devpost.com/software/tbd-72iomb,False,"As young college students, we are often poorly...",Our key features: 1) Simplify the insurance hu...,Since we wanted to implement a machine learnin...,NaN,NaN,NaN,NaN,"mapbox, python, typescript, vite",['https://github.com/leon934/hackrice2425'],['https://github.com/leon934/hackrice2425'],"The `hackrice2425` project, titled ""Insurance ..."

In [16]:
df_new_2 = pd.concat([df_new, df3], ignore_index=True)
df_new_2

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary,what_is_next
0,Cal Hacks 10.0,Audiogroph,https://devpost.com/software/audiogroph,False,With covid ending and people finding new music...,"The project shows events, creators and any NFT...",We used react to build it in vscode and collab...,We had to learn react and navigate through git...,We have successfully built the frontend of the...,Start planning earlier and commit to branches ...,We need a backend to our project.,"css3, html5, javascript, react",['https://github.com/RyanGertz/CalHacksproject'],['https://github.com/RyanGertz/CalHacksproject'],NaN
1,Cal Hacks 10.0,Let It Out,https://devpost.com/software/let-it-out-b2xp8u,False,Understanding and expressing emotions can be a...,The user is first prompted to record a vocal b...,Let It Out is a full stack web app. The front ...,The main challenges we ran into came in our fi...,NaN,We learned how to integrate modern technologie...,NaN,"chakra, flask, hume, mongodb, node.js, openai,...","['https://github.com/apolyeti/calhacks10.0,', ...",['https://github.com/apolyeti/calhacks10.0'],NaN
2,Cal Hacks 10.0,Mood Theremin,https://devpost.com/software/mood-theremin,False,"The theremin, an electronic musical instrument...",Mood Theremin translates your facial expressio...,Our project integrates facial expression analy...,NaN,NaN,NaN,NaN,"css, flask, html, hume, javascript, json, pyth...",['https://github.com/Sepulchre49/CalHacks23'],['https://github.com/Sepulchre49/CalHacks23'],NaN
3,Cal Hacks 10.0,Bay Area Safer Housing (B.A.S.H.),https://devpost.com/software/bay-area-safer-ho...,False,The inspiration initially stems from one membe...,B.A.S.H. searches for affordable housing optio...,Our website's foundation was built on next.js ...,Our difficulties lay in our inexperience with ...,"Conceptually, we believe that our project is m...",We've learned most importantly how to better a...,We are serious in our project and are intent o...,"catalog.data.gov, data.sfgov.org, google-maps,...","['https://github.com/matthewaol/b.a.s.h.,']",['https://github.com/matthewaol/b.a.s.h.'],NaN
4,Cal Hacks 10.0,PawPals,https://devpost.com/software/pawpals-bd8njs,False,"As college students, we both agreed that fun t...","Based on a list of criteria, we prompt OpenAI'...","On the front-end, we utilized Figma to develop...",Some challenges we ran into were the lack of e...,"As a team of two, we were very proud of our fi...",We learned the value of coming up with a plan ...,We hope to deploy the site on Vercel and devel...,"fastapi, figma, openai, python, react.js, sqlite",['https://github.com/Yatsz/PawPals'],['https://github.com/Yatsz/PawPals'],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7003,HackRice 14 2024,Degree Map AI,https://devpost.com/software/degree-planner-ai,False,As current undergraduate students trying to na...,Degree Map AI includes a React front-end and a...,"We first started by working on the scraper, fr...",One challenge we faced was figuring out the be...,We're proud to have successfully connected the...,"We learned to set up OpenAI's ChatGPT, scrape ...","c++, javascript, openai, pyflask, python, react",['https://github.com/april2546/HackRice2024'],['https://github.com/april2546/HackRice2024'],The HackRice2024-DegreeMapAI project is an inn...,"Given the limited amount of time, we were only..."
7004,HackRice 14 2024,Money Mania,https://devpost.com/software/money-mania,False,Our inspiration for this project was this book...,This game teaches people about personal financ...,We built this in Python using PyGame. We split...,None of us have ever participated in a hackath...,We are proud of the fact we have a finished pr...,We learned that creating a layout in PyGame is...,"pygame, python",['https://github.com/ashwinrao1/Hackathon24'],['https://github.com/ashwinrao1/Hackathon24'],"The Hackathon24 project is a ""Personal Finance...",Money Mania will have expansions in the invest...
7005,HackRice 14 2024,AudioAnalyze,https://devpost.com/software/audioanalyze-muw9zk,False,The inspiration behind this project came from ...,NaN,NaN,NaN,NaN,NaN,"ai, generative, lambda-(for-serverless-process...",['https://github.com/Ayush374/Ai_Audio_Analysis'],['https://github.com/Ayush374/Ai_Audio_Analysis'],"The GitHub repository ""Ai_Audio_Analysis"" is d...",NaN
7006,HackRice 14 2024,RestoreIO,https://devpost.com/software/tbd-ir3qd5,False,RestoreIO was created in response to the deman...,NaN,NaN,NaN,NaN,NaN,"ai, computer, computervision, love, mediapipe,...",['https://github.com/OfficialCodeVoyage/HackRi...,['https://github.com/OfficialCodeVoyage/HackRi...,"The GitHub repository ""HackRice14_RecoveryIO,""...",NaN
7007,HackRice 14 2024,MedSure,https://devpost.com/software/tbd-72iomb,False,"As young college students, we are often poorly...",Our key features: 1) Simplify the insurance hu...,Since we wanted to implement a machine learnin...,NaN,NaN,NaN,"mapbox, python, typescript, vite",['https://github.com/leon934/hackrice2425'],['https://github.com/leon934/hackrice2425'],"The `hackrice2425` project, titled ""Insurance ...",NaN

In [12]:
df_new.to_csv("analysis_dataset.csv")